export const FETCH_WEATHER_START = "FETCH_WEATHER_START";
export const FETCH_WEATHER_SUCCESS = "FETCH_WEATHER_SUCCESS";
export const FETCH_WEATHER_ERROR = "FETCH_WEATHER_ERROR";
export const ADD_TRAKKED_CITY_NAME = "ADD_TRAKKED_CITY_NAME";
export const REMOVE_TRAKKED_CITY_NAME = "REMOVE_TRAKKED_CITY_NAME";
export const FETCH_TRACKED_CITIES = "FETCH_TRACKED_CITIES";
export const FETCH_WEATHER_BY_LOCATION_SUCCESS =
  "FETCH_WEATHER_BY_LOCATION_SUCCESS";
