export const FETCH_WEATHER_BY_LOCATION_SUCCESS =
  "FETCH_WEATHER_BY_LOCATION_SUCCESS";
export const FETCH_WEATHER_BY_LOCATION_START =
  "FETCH_WEATHER_BY_LOCATION_START";
export const FETCH_WEATHER_BY_LOCATION_ERROR =
  "FETCH_WEATHER_BY_LOCATION_ERROR";
